// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ArticleCreate
 */
export type ArticleCreate = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Text
     */
    text: string;
    /**
     * Primary Image Id
     */
    primary_image_id?: string | null;
    /**
     * Background Image Id
     */
    background_image_id?: string | null;
};

/**
 * ArticleRead
 */
export type ArticleRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Text
     */
    text: string;
    /**
     * Creator Id
     */
    creator_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    primary_image: ImageRead | null;
    background_image: ImageRead | null;
};

/**
 * ArticleSearchResult
 */
export type ArticleSearchResult = {
    article: ArticleRead;
    /**
     * Rank
     */
    rank: number;
};

/**
 * ArticleUpdate
 */
export type ArticleUpdate = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Primary Image Id
     */
    primary_image_id?: string | null;
    /**
     * Background Image Id
     */
    background_image_id?: string | null;
};

/**
 * Body_login_auth_login_post
 */
export type BodyLoginAuthLoginPost = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_update_image_images__image_id__patch
 */
export type BodyUpdateImageImagesImageIdPatch = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_upload_image_images_post
 */
export type BodyUploadImageImagesPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageRead
 */
export type ImageRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Content Type
     */
    content_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    avatar: ImageRead | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Avatar Id
     */
    avatar_id?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type ListUsersUsersGetResponses = {
    /**
     * Response List Users Users Get
     *
     * Successful Response
     */
    200: Array<UserRead>;
};

export type ListUsersUsersGetResponse = ListUsersUsersGetResponses[keyof ListUsersUsersGetResponses];

export type CreateUserUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUsersPostError = CreateUserUsersPostErrors[keyof CreateUserUsersPostErrors];

export type CreateUserUsersPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type CreateUserUsersPostResponse = CreateUserUsersPostResponses[keyof CreateUserUsersPostResponses];

export type DeleteUserUsersUserIdDeleteData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type DeleteUserUsersUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUsersUserIdDeleteError = DeleteUserUsersUserIdDeleteErrors[keyof DeleteUserUsersUserIdDeleteErrors];

export type DeleteUserUsersUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type GetUserUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserUsersUserIdGetError = GetUserUsersUserIdGetErrors[keyof GetUserUsersUserIdGetErrors];

export type GetUserUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type GetUserUsersUserIdGetResponse = GetUserUsersUserIdGetResponses[keyof GetUserUsersUserIdGetResponses];

export type UpdateUserUsersUserIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/users/{user_id}';
};

export type UpdateUserUsersUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUsersUserIdPatchError = UpdateUserUsersUserIdPatchErrors[keyof UpdateUserUsersUserIdPatchErrors];

export type UpdateUserUsersUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UpdateUserUsersUserIdPatchResponse = UpdateUserUsersUserIdPatchResponses[keyof UpdateUserUsersUserIdPatchResponses];

export type ListArticlesArticlesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/articles';
};

export type ListArticlesArticlesGetResponses = {
    /**
     * Response List Articles Articles Get
     *
     * Successful Response
     */
    200: Array<ArticleRead>;
};

export type ListArticlesArticlesGetResponse = ListArticlesArticlesGetResponses[keyof ListArticlesArticlesGetResponses];

export type CreateArticleArticlesPostData = {
    body: ArticleCreate;
    path?: never;
    query?: never;
    url: '/articles';
};

export type CreateArticleArticlesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateArticleArticlesPostError = CreateArticleArticlesPostErrors[keyof CreateArticleArticlesPostErrors];

export type CreateArticleArticlesPostResponses = {
    /**
     * Successful Response
     */
    200: ArticleRead;
};

export type CreateArticleArticlesPostResponse = CreateArticleArticlesPostResponses[keyof CreateArticleArticlesPostResponses];

export type SearchArticlesArticlesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/articles/search';
};

export type SearchArticlesArticlesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchArticlesArticlesSearchGetError = SearchArticlesArticlesSearchGetErrors[keyof SearchArticlesArticlesSearchGetErrors];

export type SearchArticlesArticlesSearchGetResponses = {
    /**
     * Response Search Articles Articles Search Get
     *
     * Successful Response
     */
    200: Array<ArticleSearchResult>;
};

export type SearchArticlesArticlesSearchGetResponse = SearchArticlesArticlesSearchGetResponses[keyof SearchArticlesArticlesSearchGetResponses];

export type DeleteArticleArticlesArticleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Article Id
         */
        article_id: string;
    };
    query?: never;
    url: '/articles/{article_id}';
};

export type DeleteArticleArticlesArticleIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteArticleArticlesArticleIdDeleteError = DeleteArticleArticlesArticleIdDeleteErrors[keyof DeleteArticleArticlesArticleIdDeleteErrors];

export type DeleteArticleArticlesArticleIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetArticleArticlesArticleIdGetData = {
    body?: never;
    path: {
        /**
         * Article Id
         */
        article_id: string;
    };
    query?: never;
    url: '/articles/{article_id}';
};

export type GetArticleArticlesArticleIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetArticleArticlesArticleIdGetError = GetArticleArticlesArticleIdGetErrors[keyof GetArticleArticlesArticleIdGetErrors];

export type GetArticleArticlesArticleIdGetResponses = {
    /**
     * Successful Response
     */
    200: ArticleRead;
};

export type GetArticleArticlesArticleIdGetResponse = GetArticleArticlesArticleIdGetResponses[keyof GetArticleArticlesArticleIdGetResponses];

export type UpdateArticleArticlesArticleIdPatchData = {
    body: ArticleUpdate;
    path: {
        /**
         * Article Id
         */
        article_id: string;
    };
    query?: never;
    url: '/articles/{article_id}';
};

export type UpdateArticleArticlesArticleIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateArticleArticlesArticleIdPatchError = UpdateArticleArticlesArticleIdPatchErrors[keyof UpdateArticleArticlesArticleIdPatchErrors];

export type UpdateArticleArticlesArticleIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ArticleRead;
};

export type UpdateArticleArticlesArticleIdPatchResponse = UpdateArticleArticlesArticleIdPatchResponses[keyof UpdateArticleArticlesArticleIdPatchResponses];

export type ListImagesImagesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/images';
};

export type ListImagesImagesGetResponses = {
    /**
     * Response List Images Images Get
     *
     * Successful Response
     */
    200: Array<ImageRead>;
};

export type ListImagesImagesGetResponse = ListImagesImagesGetResponses[keyof ListImagesImagesGetResponses];

export type UploadImageImagesPostData = {
    body: BodyUploadImageImagesPost;
    path?: never;
    query?: never;
    url: '/images';
};

export type UploadImageImagesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadImageImagesPostError = UploadImageImagesPostErrors[keyof UploadImageImagesPostErrors];

export type UploadImageImagesPostResponses = {
    /**
     * Successful Response
     */
    200: ImageRead;
};

export type UploadImageImagesPostResponse = UploadImageImagesPostResponses[keyof UploadImageImagesPostResponses];

export type DeleteImageImagesImageIdDeleteData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/images/{image_id}';
};

export type DeleteImageImagesImageIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteImageImagesImageIdDeleteError = DeleteImageImagesImageIdDeleteErrors[keyof DeleteImageImagesImageIdDeleteErrors];

export type DeleteImageImagesImageIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetImageMetadataImagesImageIdGetData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/images/{image_id}';
};

export type GetImageMetadataImagesImageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageMetadataImagesImageIdGetError = GetImageMetadataImagesImageIdGetErrors[keyof GetImageMetadataImagesImageIdGetErrors];

export type GetImageMetadataImagesImageIdGetResponses = {
    /**
     * Successful Response
     */
    200: ImageRead;
};

export type GetImageMetadataImagesImageIdGetResponse = GetImageMetadataImagesImageIdGetResponses[keyof GetImageMetadataImagesImageIdGetResponses];

export type UpdateImageImagesImageIdPatchData = {
    body: BodyUpdateImageImagesImageIdPatch;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/images/{image_id}';
};

export type UpdateImageImagesImageIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateImageImagesImageIdPatchError = UpdateImageImagesImageIdPatchErrors[keyof UpdateImageImagesImageIdPatchErrors];

export type UpdateImageImagesImageIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ImageRead;
};

export type UpdateImageImagesImageIdPatchResponse = UpdateImageImagesImageIdPatchResponses[keyof UpdateImageImagesImageIdPatchResponses];

export type GetImageFileImagesImageIdRawGetData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/images/{image_id}/raw';
};

export type GetImageFileImagesImageIdRawGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImageFileImagesImageIdRawGetError = GetImageFileImagesImageIdRawGetErrors[keyof GetImageFileImagesImageIdRawGetErrors];

export type GetImageFileImagesImageIdRawGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SimilarImagesImagesImageIdSimilarGetData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/images/{image_id}/similar';
};

export type SimilarImagesImagesImageIdSimilarGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SimilarImagesImagesImageIdSimilarGetError = SimilarImagesImagesImageIdSimilarGetErrors[keyof SimilarImagesImagesImageIdSimilarGetErrors];

export type SimilarImagesImagesImageIdSimilarGetResponses = {
    /**
     * Response Similar Images Images  Image Id  Similar Get
     *
     * Successful Response
     */
    200: Array<ImageRead>;
};

export type SimilarImagesImagesImageIdSimilarGetResponse = SimilarImagesImagesImageIdSimilarGetResponses[keyof SimilarImagesImagesImageIdSimilarGetResponses];

export type SearchImagesImagesSearchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/images/search';
};

export type SearchImagesImagesSearchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchImagesImagesSearchGetError = SearchImagesImagesSearchGetErrors[keyof SearchImagesImagesSearchGetErrors];

export type SearchImagesImagesSearchGetResponses = {
    /**
     * Response Search Images Images Search Get
     *
     * Successful Response
     */
    200: Array<ImageRead>;
};

export type SearchImagesImagesSearchGetResponse = SearchImagesImagesSearchGetResponses[keyof SearchImagesImagesSearchGetResponses];

export type LoginAuthLoginPostData = {
    body: BodyLoginAuthLoginPost;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type MeAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type MeAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
