"""full text search initial

Revision ID: 9659dcbabe62
Revises: 7f16409ca6ee
Create Date: 2026-06-16 01:30:10.494787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9659dcbabe62'
down_revision: Union[str, Sequence[str], None] = '7f16409ca6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(display_name, '') || ' ' || coalesce(text, ''))", persisted=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'search_vector')
    # ### end Alembic commands ###
